= Overview

Welcome,

This section shows how to set up Simple Java application named galaxy-merchant. Then it shows how to build a simple UI on top of it by using Facebook's React.js toolset.
This repository aim to be an assignment test for back-end programmer challenge. This demo uses Java 8, Maven Project, and the latest stable release of Spring Boot. 
It also uses React.js coded in http://es6-features.org/[ES6].


= Prerequisites

* Java 8 (prefer JDK than JRE)
* Maven 3
* Git
* Any IDE / other text editor compatible for Java development (Eclipse, netbeans, intellij IDEA etc.)

= Get the source code
Make sure you have already installed git on your computer.
Clone this https://github.com/Azzuarezh/galaxy-merchant/[repository] with the following steps :

* open command prompt and go to the directory that you want the app to be downloaded.
* when you have already there, type command below:

....
git clone https://github.com/Azzuarezh/galaxy-merchant.git
....

* Wait until it finished downloading the source, after finished we can go to the IDE or any text editor to open the project. ( make sure the IDE has already integrated with Java)

= Build and Run the application

there are two Mode for this application. CLI version and Web version. By default, the application will build the CLI version. This section will explain to accomplish both modes.

== CLI Version

run maven on command prompt/terminal and type following syntax :
....
# windows
mvnw.cmd clean package

# linux
./mvnw clean package
....

== web version

run maven on command prompt/terminal and type following syntax :
....
# windows
mvnw.cmd clean package -Pweb

# linux
./mvnw clean package -Pweb
....

After finished build the JAR file, go to `target/` folder. It will generate JAR file named `galaxy-merchant-<version>.jar` (the version is based on version tag in `pom.xml` file).

in command prompt/terminal and go to `target` folder then type following command :

....
java -jar galaxy-merchant-<version>.jar
....



= Testing

To see the test report for this app, you can run the following command on command prompt/terminal :

....
# windows
mvnw.cmd clean test site

# linux
./mvnw clean test site
....

It will produce folder `site` in `target` directory. open `index.html` to see the report. Click `Project Report > Surefire Report` on the left side menu.

If you have any issues regarding to install/running the app, please contact me on mailto:muh.thahir27@gmail.com/[email]
